In [4]:
import cv2
import numpy as np
import os
import pandas as pd

### How to play video in OpenCV (cv2.VideoCapture)

In [8]:
vid = cv2.VideoCapture(r"C:\Users\91912\Downloads\WhatsApp Video 2024-11-26 at 12.11.28 PM.mp4")

while True:
    succ,img = vid.read()  # it gives two outputs(1-frames of video and 2-boolean value according into presence of frame in vid)

    if succ == False:
        break

    cv2.imshow("video",img)
    
    if cv2.waitKey(100) & 255 == ord("a"):
        break

cv2.destroyAllWindows()

#### Converting Video to Grey Scale

In [13]:
vid = cv2.VideoCapture(r"C:\Users\91912\Downloads\WhatsApp Video 2024-11-26 at 12.11.28 PM.mp4")

while True:
    succ,img = vid.read()

    if succ == False:
        break
        
    img1 = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) # Convert bgr image to grey scale
    cv2.imshow("video",img)
    cv2.imshow("video_grey",img1)
    
    if cv2.waitKey(100) & 255 == ord("a"):
        break

cv2.destroyAllWindows()

#### Converting Video to B,G,R shades

In [16]:
vid = cv2.VideoCapture(r"C:\Users\91912\Downloads\WhatsApp Video 2024-11-26 at 12.11.28 PM.mp4")

while True:
    succ,img = vid.read()

    if succ == False:
        break

    b,g,r = cv2.split(img)
    z = np.zeros(b.shape,dtype = np.uint8)

    img1 = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    cv2.imshow("Grey",img1)
    cv2.imshow("blue",cv2.merge([b,z,z]))
    cv2.imshow("Green",cv2.merge([z,g,z]))
    cv2.imshow("Red",cv2.merge([z,z,r]))
    cv2.imshow("video",img)
    
    if cv2.waitKey(100) & 255 == ord("a"):
        break

cv2.destroyAllWindows()

#### Converting Videos to Tabular Structure

In [19]:
os.mkdir(r"C:\Users\91912\OneDrive\Documents\Animals\Cat")
os.mkdir(r"C:\Users\91912\OneDrive\Documents\Animals\Dog")
os.mkdir(r"C:\Users\91912\OneDrive\Documents\Animals\Elephant")

In [23]:
l = os.listdir(r"C:\Users\91912\OneDrive\Documents\Animals")
l

['Cat', 'Cat.mp4', 'Dog', 'Dog.mp4', 'Elephant', 'Elephant.mp4']

In [25]:
l1 = []
for i in l:
    if i.endswith(".mp4"):
        l1.append(i)

In [27]:
l1

['Cat.mp4', 'Dog.mp4', 'Elephant.mp4']

In [29]:
for video in l1:
    vid = cv2.VideoCapture(r"C:\Users\91912\OneDrive\Documents\Animals\{}".format(video))
    c = 0
    while True:
        succ,img = vid.read()

        if succ == False:
            break
        cv2.imwrite(r"C:\Users\91912\OneDrive\Documents\Animals\{}\{}{}.jpg".format(video.split(".")[0],video.split(".")[0],c),img)
        c += 1
        
        cv2.imshow("vid",img)
        if cv2.waitKey(100) & 255 == ord("a"):
            break

    cv2.destroyAllWindows()

In [31]:
l2 = []
for i in l:
    if not i.endswith(".mp4"):
        l2.append(i)

In [33]:
l2

['Cat', 'Dog', 'Elephant']

In [35]:
features = []
class_labels = []
for i in l2:
    for images in os.listdir(r"C:\Users\91912\OneDrive\Documents\Animals\{}".format(i)):
        img = cv2.imread(r"C:\Users\91912\OneDrive\Documents\Animals\{}\{}".format(i,images),0)
        img = cv2.resize(img,(50,50)) # resize the image
        img = img.flatten()  # Falttening array
        features.append(img)
        class_labels.append(i)

In [37]:
df = pd.DataFrame(features)

In [39]:
df["Class_labels"] = class_labels

In [41]:
df

,0,1,2,3,4,5,6,7,8,9,...,2491,2492,2493,2494,2495,2496,2497,2498,2499,Class_labels
0,15,12,14,16,17,12,11,9,11,10,...,169,176,165,89,90,94,99,102,105,Cat
1,15,12,14,16,17,12,11,9,11,10,...,169,176,164,89,92,94,99,102,105,Cat
2,14,12,14,16,17,12,11,9,11,10,...,171,176,158,112,112,111,117,125,127,Cat
3,15,12,13,15,18,17,12,10,10,10,...,171,173,130,60,61,63,65,64,65,Cat
4,15,12,13,15,18,17,12,10,10,10,...,170,173,119,58,60,62,63,63,64,Cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,127,158,135,104,102,149,201,105,166,116,...,163,163,160,155,151,152,156,162,163,Elephant
708,122,154,132,104,96,146,186,107,175,117,...,162,160,159,155,152,149,151,157,158,Elephant
709,127,154,132,104,96,146,186,107,175,117,...,162,160,159,155,152,149,151,157,161,Elephant
710,129,152,130,108,96,147,186,110,177,110,...,162,158,159,154,151,150,152,149,154,Elephant
711,129,153,130,108,96,147,186,110,177,110,...,161,158,159,154,151,150,152,150,154,Elephant

In [43]:
df.to_csv(r"C:\Users\91912\OneDrive\Documents\Animals.csv")